server:
  port: 9527
spring:
  application:
    name: springcloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
#      ,http://localhost:7002/eureka/,
#      http://localhost/eureka/
  instance:
    instance-id: zuul9527.com
    prefer-ip-address: true
info:
  app.name: yunspringcloud
  company.name: blog.yun.com
Zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
  ignored-services: springcloud-provider-dept #不能在使用这个路径访问
